// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRAuCunwKbpD5coyLONUGlyN9xP5nSAsA',
    appId: '1:333223996683:web:d4263690d0c44476d1c60e',
    messagingSenderId: '333223996683',
    projectId: 'pizza-app-227c1',
    authDomain: 'pizza-app-227c1.firebaseapp.com',
    storageBucket: 'pizza-app-227c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbf07invutLCwY7QtmGtgIxbmTiGtGBLI',
    appId: '1:333223996683:android:8fee6b0d60d59611d1c60e',
    messagingSenderId: '333223996683',
    projectId: 'pizza-app-227c1',
    storageBucket: 'pizza-app-227c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfJL2dWqXbG-Cfwa70_Y1zHWWzIaBB7-A',
    appId: '1:333223996683:ios:d3500d527c76a7aed1c60e',
    messagingSenderId: '333223996683',
    projectId: 'pizza-app-227c1',
    storageBucket: 'pizza-app-227c1.firebasestorage.app',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfJL2dWqXbG-Cfwa70_Y1zHWWzIaBB7-A',
    appId: '1:333223996683:ios:d3500d527c76a7aed1c60e',
    messagingSenderId: '333223996683',
    projectId: 'pizza-app-227c1',
    storageBucket: 'pizza-app-227c1.firebasestorage.app',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRAuCunwKbpD5coyLONUGlyN9xP5nSAsA',
    appId: '1:333223996683:web:2896fcbc70da9721d1c60e',
    messagingSenderId: '333223996683',
    projectId: 'pizza-app-227c1',
    authDomain: 'pizza-app-227c1.firebaseapp.com',
    storageBucket: 'pizza-app-227c1.firebasestorage.app',
  );

}